import { defineWidgetConfig } from "@medusajs/admin-sdk"
import { AdminHelpDrawer } from "../components/admin-help-drawer"

const AdminHelpDrawerWidget = () => {
  return <AdminHelpDrawer />
}

export const config = defineWidgetConfig({
  zone: [
    "order.list.before",
    "order.details.before",
    "order.details.side.before",
    "customer.details.before",
    "customer.details.side.before",
    "customer.list.before",
    "customer_group.details.before",
    "customer_group.list.before",
    "product.list.before",
    "product.details.before",
    "product.details.side.before",
    "product_variant.details.before",
    "product_variant.details.side.before",
    "product_collection.details.before",
    "product_collection.list.before",
    "product_category.details.before",
    "product_category.details.side.before",
    "product_category.list.before",
    "product_type.details.before",
    "product_type.list.before",
    "shipping_option_type.details.before",
    "shipping_option_type.list.before",
    "product_tag.details.before",
    "product_tag.list.before",
    "price_list.details.before",
    "price_list.details.side.before",
    "price_list.list.before",
    "promotion.details.before",
    "promotion.details.side.before",
    "promotion.list.before",
    "user.details.before",
    "user.list.before",
    "store.details.before",
    "profile.details.before",
    "region.details.before",
    "region.list.before",
    "shipping_profile.details.before",
    "shipping_profile.list.before",
    "location.details.before",
    "location.details.side.before",
    "location.list.before",
    "location.list.side.before",
    "sales_channel.details.before",
    "sales_channel.list.before",
    "reservation.details.before",
    "reservation.details.side.before",
    "reservation.list.before",
    "api_key.details.before",
    "api_key.list.before",
    "workflow.details.before",
    "workflow.list.before",
    "campaign.details.before",
    "campaign.details.side.before",
    "campaign.list.before",
    "tax.details.before",
    "tax.list.before",
    "return_reason.list.before",
    "refund_reason.list.before",
    "inventory_item.details.before",
    "inventory_item.details.side.before",
    "inventory_item.list.before",
  ],
})

export default AdminHelpDrawerWidget
